// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function for the type MockService
func (_mock *MockService) Upload(ctx context.Context, userID int, orderNum string) error {
	ret := _mock.Called(ctx, userID, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, orderNum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - orderNum string
func (_e *MockService_Expecter) Upload(ctx interface{}, userID interface{}, orderNum interface{}) *MockService_Upload_Call {
	return &MockService_Upload_Call{Call: _e.mock.On("Upload", ctx, userID, orderNum)}
}

func (_c *MockService_Upload_Call) Run(run func(ctx context.Context, userID int, orderNum string)) *MockService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Upload_Call) Return(err error) *MockService_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Upload_Call) RunAndReturn(run func(ctx context.Context, userID int, orderNum string) error) *MockService_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GetUserID provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetUserID(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockAuthService_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthService_Expecter) GetUserID(ctx interface{}) *MockAuthService_GetUserID_Call {
	return &MockAuthService_GetUserID_Call{Call: _e.mock.On("GetUserID", ctx)}
}

func (_c *MockAuthService_GetUserID_Call) Run(run func(ctx context.Context)) *MockAuthService_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_GetUserID_Call) Return(n int, err error) *MockAuthService_GetUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAuthService_GetUserID_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockAuthService_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}
