// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package order

import (
	"context"

	"github.com/Dmitriy-Shcheklein/gophermart/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateOrder(ctx context.Context, userID int, orderNum string) error {
	ret := _mock.Called(ctx, userID, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, orderNum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - orderNum string
func (_e *MockRepository_Expecter) CreateOrder(ctx interface{}, userID interface{}, orderNum interface{}) *MockRepository_CreateOrder_Call {
	return &MockRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, orderNum)}
}

func (_c *MockRepository_CreateOrder_Call) Run(run func(ctx context.Context, userID int, orderNum string)) *MockRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CreateOrder_Call) Return(err error) *MockRepository_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userID int, orderNum string) error) *MockRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByNum provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOrderByNum(ctx context.Context, orderNum string) (models.DbOrder, error) {
	ret := _mock.Called(ctx, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNum")
	}

	var r0 models.DbOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.DbOrder, error)); ok {
		return returnFunc(ctx, orderNum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.DbOrder); ok {
		r0 = returnFunc(ctx, orderNum)
	} else {
		r0 = ret.Get(0).(models.DbOrder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetOrderByNum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByNum'
type MockRepository_GetOrderByNum_Call struct {
	*mock.Call
}

// GetOrderByNum is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
func (_e *MockRepository_Expecter) GetOrderByNum(ctx interface{}, orderNum interface{}) *MockRepository_GetOrderByNum_Call {
	return &MockRepository_GetOrderByNum_Call{Call: _e.mock.On("GetOrderByNum", ctx, orderNum)}
}

func (_c *MockRepository_GetOrderByNum_Call) Run(run func(ctx context.Context, orderNum string)) *MockRepository_GetOrderByNum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetOrderByNum_Call) Return(dbOrder models.DbOrder, err error) *MockRepository_GetOrderByNum_Call {
	_c.Call.Return(dbOrder, err)
	return _c
}

func (_c *MockRepository_GetOrderByNum_Call) RunAndReturn(run func(ctx context.Context, orderNum string) (models.DbOrder, error)) *MockRepository_GetOrderByNum_Call {
	_c.Call.Return(run)
	return _c
}
