// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package order

import (
	"context"
	"iter"

	"github.com/Dmitriy-Shcheklein/gophermart/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateOrder(ctx context.Context, userID int, orderNum string) error {
	ret := _mock.Called(ctx, userID, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, orderNum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - orderNum string
func (_e *MockRepository_Expecter) CreateOrder(ctx interface{}, userID interface{}, orderNum interface{}) *MockRepository_CreateOrder_Call {
	return &MockRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, orderNum)}
}

func (_c *MockRepository_CreateOrder_Call) Run(run func(ctx context.Context, userID int, orderNum string)) *MockRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CreateOrder_Call) Return(err error) *MockRepository_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userID int, orderNum string) error) *MockRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserId provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByUserId(ctx context.Context, userID int) ([]models.DbOrder, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserId")
	}

	var r0 []models.DbOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.DbOrder, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.DbOrder); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DbOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserId'
type MockRepository_GetByUserId_Call struct {
	*mock.Call
}

// GetByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepository_Expecter) GetByUserId(ctx interface{}, userID interface{}) *MockRepository_GetByUserId_Call {
	return &MockRepository_GetByUserId_Call{Call: _e.mock.On("GetByUserId", ctx, userID)}
}

func (_c *MockRepository_GetByUserId_Call) Run(run func(ctx context.Context, userID int)) *MockRepository_GetByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByUserId_Call) Return(dbOrders []models.DbOrder, err error) *MockRepository_GetByUserId_Call {
	_c.Call.Return(dbOrders, err)
	return _c
}

func (_c *MockRepository_GetByUserId_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]models.DbOrder, error)) *MockRepository_GetByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByNum provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOrderByNum(ctx context.Context, orderNum string) (models.DbOrder, error) {
	ret := _mock.Called(ctx, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNum")
	}

	var r0 models.DbOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.DbOrder, error)); ok {
		return returnFunc(ctx, orderNum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.DbOrder); ok {
		r0 = returnFunc(ctx, orderNum)
	} else {
		r0 = ret.Get(0).(models.DbOrder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetOrderByNum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByNum'
type MockRepository_GetOrderByNum_Call struct {
	*mock.Call
}

// GetOrderByNum is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
func (_e *MockRepository_Expecter) GetOrderByNum(ctx interface{}, orderNum interface{}) *MockRepository_GetOrderByNum_Call {
	return &MockRepository_GetOrderByNum_Call{Call: _e.mock.On("GetOrderByNum", ctx, orderNum)}
}

func (_c *MockRepository_GetOrderByNum_Call) Run(run func(ctx context.Context, orderNum string)) *MockRepository_GetOrderByNum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetOrderByNum_Call) Return(dbOrder models.DbOrder, err error) *MockRepository_GetOrderByNum_Call {
	_c.Call.Return(dbOrder, err)
	return _c
}

func (_c *MockRepository_GetOrderByNum_Call) RunAndReturn(run func(ctx context.Context, orderNum string) (models.DbOrder, error)) *MockRepository_GetOrderByNum_Call {
	_c.Call.Return(run)
	return _c
}

// GetProcessingOrders provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProcessingOrders(ctx context.Context) iter.Seq[models.DbOrder] {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProcessingOrders")
	}

	var r0 iter.Seq[models.DbOrder]
	if returnFunc, ok := ret.Get(0).(func(context.Context) iter.Seq[models.DbOrder]); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[models.DbOrder])
		}
	}
	return r0
}

// MockRepository_GetProcessingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcessingOrders'
type MockRepository_GetProcessingOrders_Call struct {
	*mock.Call
}

// GetProcessingOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetProcessingOrders(ctx interface{}) *MockRepository_GetProcessingOrders_Call {
	return &MockRepository_GetProcessingOrders_Call{Call: _e.mock.On("GetProcessingOrders", ctx)}
}

func (_c *MockRepository_GetProcessingOrders_Call) Run(run func(ctx context.Context)) *MockRepository_GetProcessingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetProcessingOrders_Call) Return(seq iter.Seq[models.DbOrder]) *MockRepository_GetProcessingOrders_Call {
	_c.Call.Return(seq)
	return _c
}

func (_c *MockRepository_GetProcessingOrders_Call) RunAndReturn(run func(ctx context.Context) iter.Seq[models.DbOrder]) *MockRepository_GetProcessingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBalance provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserBalance(ctx context.Context, useID int) (models.DbBalance, error) {
	ret := _mock.Called(ctx, useID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 models.DbBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.DbBalance, error)); ok {
		return returnFunc(ctx, useID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.DbBalance); ok {
		r0 = returnFunc(ctx, useID)
	} else {
		r0 = ret.Get(0).(models.DbBalance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, useID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type MockRepository_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - useID int
func (_e *MockRepository_Expecter) GetUserBalance(ctx interface{}, useID interface{}) *MockRepository_GetUserBalance_Call {
	return &MockRepository_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, useID)}
}

func (_c *MockRepository_GetUserBalance_Call) Run(run func(ctx context.Context, useID int)) *MockRepository_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserBalance_Call) Return(dbBalance models.DbBalance, err error) *MockRepository_GetUserBalance_Call {
	_c.Call.Return(dbBalance, err)
	return _c
}

func (_c *MockRepository_GetUserBalance_Call) RunAndReturn(run func(ctx context.Context, useID int) (models.DbBalance, error)) *MockRepository_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawals provides a mock function for the type MockRepository
func (_mock *MockRepository) GetWithdrawals(ctx context.Context, userID int) ([]models.DbWithdrawn, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []models.DbWithdrawn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.DbWithdrawn, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.DbWithdrawn); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DbWithdrawn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type MockRepository_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepository_Expecter) GetWithdrawals(ctx interface{}, userID interface{}) *MockRepository_GetWithdrawals_Call {
	return &MockRepository_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, userID)}
}

func (_c *MockRepository_GetWithdrawals_Call) Run(run func(ctx context.Context, userID int)) *MockRepository_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetWithdrawals_Call) Return(dbWithdrawns []models.DbWithdrawn, err error) *MockRepository_GetWithdrawals_Call {
	_c.Call.Return(dbWithdrawns, err)
	return _c
}

func (_c *MockRepository_GetWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]models.DbWithdrawn, error)) *MockRepository_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateOrder(ctx context.Context, order models.DbOrder) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DbOrder) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type MockRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.DbOrder
func (_e *MockRepository_Expecter) UpdateOrder(ctx interface{}, order interface{}) *MockRepository_UpdateOrder_Call {
	return &MockRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *MockRepository_UpdateOrder_Call) Run(run func(ctx context.Context, order models.DbOrder)) *MockRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.DbOrder
		if args[1] != nil {
			arg1 = args[1].(models.DbOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateOrder_Call) Return(err error) *MockRepository_UpdateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateOrder_Call) RunAndReturn(run func(ctx context.Context, order models.DbOrder) error) *MockRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockRepository
func (_mock *MockRepository) Withdraw(ctx context.Context, balance models.DbBalance, withdrawn models.DbWithdrawn) error {
	ret := _mock.Called(ctx, balance, withdrawn)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DbBalance, models.DbWithdrawn) error); ok {
		r0 = returnFunc(ctx, balance, withdrawn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockRepository_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - balance models.DbBalance
//   - withdrawn models.DbWithdrawn
func (_e *MockRepository_Expecter) Withdraw(ctx interface{}, balance interface{}, withdrawn interface{}) *MockRepository_Withdraw_Call {
	return &MockRepository_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, balance, withdrawn)}
}

func (_c *MockRepository_Withdraw_Call) Run(run func(ctx context.Context, balance models.DbBalance, withdrawn models.DbWithdrawn)) *MockRepository_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.DbBalance
		if args[1] != nil {
			arg1 = args[1].(models.DbBalance)
		}
		var arg2 models.DbWithdrawn
		if args[2] != nil {
			arg2 = args[2].(models.DbWithdrawn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Withdraw_Call) Return(err error) *MockRepository_Withdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Withdraw_Call) RunAndReturn(run func(ctx context.Context, balance models.DbBalance, withdrawn models.DbWithdrawn) error) *MockRepository_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoyaltyService creates a new instance of MockLoyaltyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoyaltyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoyaltyService {
	mock := &MockLoyaltyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoyaltyService is an autogenerated mock type for the LoyaltyService type
type MockLoyaltyService struct {
	mock.Mock
}

type MockLoyaltyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoyaltyService) EXPECT() *MockLoyaltyService_Expecter {
	return &MockLoyaltyService_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockLoyaltyService
func (_mock *MockLoyaltyService) GetOrder(ctx context.Context, orderNum string) (models.LoyaltyOrderData, error) {
	ret := _mock.Called(ctx, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 models.LoyaltyOrderData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.LoyaltyOrderData, error)); ok {
		return returnFunc(ctx, orderNum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.LoyaltyOrderData); ok {
		r0 = returnFunc(ctx, orderNum)
	} else {
		r0 = ret.Get(0).(models.LoyaltyOrderData)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockLoyaltyService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
func (_e *MockLoyaltyService_Expecter) GetOrder(ctx interface{}, orderNum interface{}) *MockLoyaltyService_GetOrder_Call {
	return &MockLoyaltyService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderNum)}
}

func (_c *MockLoyaltyService_GetOrder_Call) Run(run func(ctx context.Context, orderNum string)) *MockLoyaltyService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyService_GetOrder_Call) Return(loyaltyOrderData models.LoyaltyOrderData, err error) *MockLoyaltyService_GetOrder_Call {
	_c.Call.Return(loyaltyOrderData, err)
	return _c
}

func (_c *MockLoyaltyService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderNum string) (models.LoyaltyOrderData, error)) *MockLoyaltyService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}
