// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package order

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// SetBalance provides a mock function for the type MockRepository
func (_mock *MockRepository) SetBalance(ctx context.Context, userID int, balance float64) error {
	ret := _mock.Called(ctx, userID, balance)

	if len(ret) == 0 {
		panic("no return value specified for SetBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, float64) error); ok {
		r0 = returnFunc(ctx, userID, balance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBalance'
type MockRepository_SetBalance_Call struct {
	*mock.Call
}

// SetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - balance float64
func (_e *MockRepository_Expecter) SetBalance(ctx interface{}, userID interface{}, balance interface{}) *MockRepository_SetBalance_Call {
	return &MockRepository_SetBalance_Call{Call: _e.mock.On("SetBalance", ctx, userID, balance)}
}

func (_c *MockRepository_SetBalance_Call) Run(run func(ctx context.Context, userID int, balance float64)) *MockRepository_SetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetBalance_Call) Return(err error) *MockRepository_SetBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetBalance_Call) RunAndReturn(run func(ctx context.Context, userID int, balance float64) error) *MockRepository_SetBalance_Call {
	_c.Call.Return(run)
	return _c
}
